### ISSUE TITLE
Provide a mechanism for supplying headers to return with static files

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-expressive-swoole#10]
As noted on #6, the functionality for serving static files introduced in #5, while performant, does not allow us to supply things like Cache-Control, ETag, and other HTTP-caching related headers, which can help reduce the number of repeated calls a client needs to make to the site.

Ideally, we should allow configuring such headers, and emit them for any static file served. (Eventually, we may also want to provide an block-list of files that should _never_ have such headers emitted and/or an allow-list of files that will receive the headers.)

**Comment by huangzhhui** [comment]
I’ve been finished this feature, after the pr that I submitted before merged, I will create a pr and merge into master branch.
