### ISSUE TITLE
Working directory when daemonized

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-expressive-swoole#15]
In experimenting with current master, I discovered a problem: when you run the application using the `--daemonize` or `-d` switch, errors occur when you attempt file access relative to the project root.

I was able to determine that this is because the workers _are not spawned with `PWD` equal to the project root, but instead equal to `/` (system root!). As such, we need to set the worker environment to mimic that of the manager.

**Comment by weierophinney** [comment]
As an example, I have a file in `data/packages.json`, which my controller then retrieves using `file_get_contents('data/packages.json')`. When running without the `-d` or `--daemonize` switches, this works as expected: the process is running from the project root, so the file is resolved from that location, and PHP continues on.

When daemonized (and only when daemonized; number of workers does not affect this), the workers execute with `PWD` set to the system root instead.

This is likely a problem with Swoole itself, unless there's a configuration option we are missing that controls whether or not workers inherit the environment from the manager.

@huangzhhui , do you have any ideas?

**Comment by weierophinney** [comment]
Ooof... found [this note in the Swoole docs regarding the `daemonize` option](https://www.swoole.co.uk/docs/modules/swoole-server/configuration#daemonize):

> After daemonizing the processes, the value of CWD will change and the relative path of file will be different. So it must use absolute path in the program. 

This is problematic, as one of the architectural decisions we made was to `chdir(__DIR__)` in our bootstrap, so as to avoid usage of absolute paths. We may need to either reconsider that, or ask the Swoole team for a configuration option to allow passing the `PWD` to the worker processes.

**Comment by huangzhhui** [comment]
@weierophinney This is what design about daemon mode in Linux, we can reset `CWD` after server start.

**Comment by weierophinney** [comment]
@huangzhhui I'm re-opening this, as I'm observing the problem again on current master. Specifically, I'm seeing it when using `SWOOLE_PROCESS` as the server mode; using `SWOOLE_BASE` continues to work fine. That said, if we cannot resolve getting this running under `SWOOLE_PROCESS`, we'd need to likely rethink whether or not we want to allow using that mode, as the results are inconsistent.

I tried locally adding some code to `RequestHandlerSwooleRunner::onStart()` to log the current working directory. It logs what is expected. However, any file operations that use paths relative to the `CWD` fail at that point. My suspicion is that the manager process spawning the workers is not operating from the `CWD`; however, if that were the case, why would `onStart()` report the correct directory? Doesn't that method only trigger for workers?

Any help you can provide would be greatly appreciated.

Thanks!

**Comment by weierophinney** [comment]
@huangzhhui I've solved it locally by adding a `workerstart` listener, which then calls `chdir($this->cwd)`; I'll commit the patch shortly. If you know of any pitfalls to doing this, please let me know.
