### ISSUE TITLE
$_SERVER miss some important keys

### ISSUE THREAD

**Issue by jgalvezsoax** [zendframework/zend-expressive-swoole#33]
Hello,

As I said in issue #32 , the $_SERVER var miss some important keys like _HTTP_HOST_, _HTTP_USER_AGENT_... when you do an HTTP request.

A typical $_SERVER var in a Nginx server show as next:

```
Array
(
    [USER] => www-data
    [HOME] => /var/www
    [HTTP_CACHE_CONTROL] => max-age=0
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_CONNECTION] => keep-alive
    [HTTP_COOKIE] => PHPSESSID=ro1oc6i2u42l1scn2avlsss8l5
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_ACCEPT_LANGUAGE] => es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
    [HTTP_HOST] => localhost:8910
    [APPLICATION_ENV] => production
    [SERVER_NAME] => 
    [SERVER_PORT] => 80
    [SERVER_ADDR] => 192.168.80.2
    [REMOTE_PORT] => 46794
    [REMOTE_ADDR] => 192.168.80.1
    [SERVER_SOFTWARE] => nginx
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [DOCUMENT_ROOT] => /var/www/public
    [DOCUMENT_URI] => /index.php
    [REQUEST_URI] => /microservice/pdf
    [SCRIPT_FILENAME] => /var/www/public/index.php
    [SCRIPT_NAME] => /index.php
    [CONTENT_LENGTH] => 
    [CONTENT_TYPE] => 
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [PATH_TRANSLATED] => /var/www/public
    [PATH_INFO] => 
    [DN] => 
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1537960083.3503
    [REQUEST_TIME] => 1537960083
)
```

But if you do a `$request->getServerParams() `in your handler you can see $_SERVER miss many keys

```
Array
(
    [QUERY_STRING] => getvar=getvalue
    [REQUEST_METHOD] => POST
    [REQUEST_URI] => /document
    [PATH_INFO] => /document
    [REQUEST_TIME] => 1537958456
    [REQUEST_TIME_FLOAT] => 1537958457.4177
    [SERVER_PORT] => 80
    [REMOTE_PORT] => 49168
    [REMOTE_ADDR] => 192.168.4.20
    [MASTER_TIME] => 1537958456
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => swoole-http-server
)
```

Also, if you inspect the `$request->server` property in `Zend\Expressive\Swoole\SwooleRequestHandlerRunner::onRequest` you can see the keys are different too

```
Array
(
    [HOSTNAME] => nnode
    [PWD] => /var/www
    [HOME] => /root
    [affinity:container] => =9a6cd4c7a947936e067b172056fb0512f74503cfed9b636e3f8eb8bc3095a613
    [PHP_APP_SUPPORT] => jgalvez@soax.es
    [TERM] => xterm
    [SHLVL] => 1
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [OLDPWD] => /
    [_] => /usr/bin/php
    [PHP_SELF] => public/index.php
    [SCRIPT_NAME] => public/index.php
    [SCRIPT_FILENAME] => public/index.php
    [PATH_TRANSLATED] => public/index.php
    [DOCUMENT_ROOT] => 
    [REQUEST_TIME_FLOAT] => 1537958454.4858
    [REQUEST_TIME] => 1537958454
    [argv] => Array
        (
            [0] => public/index.php
            [1] => start
        )

    [argc] => 2
    [SHELL_VERBOSITY] => 0
)
```

You can see that the last $_SERVER var is the correspondent to a php cli environment.

Could it be possible to have, approximately, the same keys than in Nginx server for $_SERVER var and $request->getServerParams()?

**Comment by huangzhhui** [comment]
@jgalvezsoax Actually all begin with `HTTP` parameters are belongs to Header of HTTP Request, not Server parameters, you could get these value via `$request->getHeaders()`

**Comment by jgalvezsoax** [comment]
Indeed @huangzhhui , HTTP_ parameters are in $request->getHeaders(), I didn't know it.

```
Array
(
    [content-type] => Array
        (
            [0] => multipart/form-data; boundary=--------------------------153560298166903737033389
        )

    [cache-control] => Array
        (
            [0] => no-cache
        )

    [postman-token] => Array
        (
            [0] => 60c27c86-904c-420e-a6b7-12f0bda8355c
        )

    [authorization] => Array
        (
            [0] => Basic STFkMWdYYWNDcFNnNUpuaTZ5WmdDWTc4MzpCZWZxU0tGN1pWeXJZNDd5QTJveE5BYkNST0NuYjV3aHNtMElVaUUzY24xOFFLUW9sSg==
        )

    [user-agent] => Array
        (
            [0] => PostmanRuntime/7.3.0
        )

    [accept] => Array
        (
            [0] => */*
        )

    [accept-encoding] => Array
        (
            [0] => gzip, deflate
        )

    [content-length] => Array
        (
            [0] => 171
        )

    [connection] => Array
        (
            [0] => keep-alive
        )

    [Host] => Array
        (
            [0] => 192.168.4.20:8912
        )

)
```
But the names of the keys are not the standard shown in php documentation - http://php.net/manual/en/reserved.variables.server.php - so it could be very difficult to adjust an existing application to work with the Zend Expressive Swoole implementation.

I still think it should appear in `$_SERVER` and `$request->getServerParams()`

Thank for your help

**Comment by huangzhhui** [comment]
It's impossible appear these parameters in `$_SERVER`, `$_SERVER` is a global functions, it will mixed the parameters between different requests in same worker.
And whether if these parameters should appear in `$request->getServerParams()`, lets zend team make this decision. @weierophinney

**Comment by ezimuel** [comment]
@jgalvezsoax you are missing the main point here. The `zend-expressive-swoole` is a library to execute [Expressive](https://getexpressive.org/) application using Swoole. That means you need to code using [PSR-7] request and response, no usage of global variables like $_SERVER or $_GET, $_POST, etc.

**Comment by jgalvezsoax** [comment]
@ezimuel now I know I can't use global vars in Zend Expressive Swoole (thanks for opening my eyes), but, what about to get the standard $_SERVER keys through `$request->getServerParams()` ?  

Actually to get the HTTP_params you must call `$request->getHeaders()`. Maybe I'm wrong but I think it's not where it is expected to be found.

Anyway thanks for your help
