### ISSUE TITLE
StartCommand assumes project is using the programmatic approach

### ISSUE THREAD

**Issue by acelaya** [zendframework/zend-expressive-swoole#51]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-swoole/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-swoole/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I'm trying to add zend-expressive-swoole ^2.0 to an existing expressive project, and it fails when running the  `start` command with the error `Fatal error: require(): Failed opening required 'config/pipeline.php'`.

I have checked the `StartCommand` code and seen that it always tries to require both `config/pipeline.php` and `config/routes.php`.

Since my project is configuration based, it fiails because those files do not exist.

Is this behavior intended? If not, I could provide a PR which makes sure the command checks those files exist before trying to require them.

**Comment by acelaya** [comment]
By the moment I have just workaround this by creating those files returning a dummy empty function.

**Comment by xtreamwayz** [comment]
Related to these lines:

https://github.com/zendframework/zend-expressive-swoole/blob/afc917244fa6b701b728fca0cb6f78c2c96767f8/src/Command/StartCommand.php#L95-L98

The pipeline and routes config are always loaded. They should only load if those files exist. Better yet, there should be a separate check for each in case someone mixes configuration-driven and programmatic pipelines and routes.

**Comment by acelaya** [comment]
Sure!

**Comment by acelaya** [comment]
Just provided a PR #52 

I'm waiting to see if the build passes.
