### ISSUE TITLE
Allowing to provide a custom psr-3 logger via configuration

### ISSUE THREAD

**Issue by acelaya** [zendframework/zend-expressive-swoole#53]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-swoole/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-swoole/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I have seen the documentation explains how to configure the logger used to log requests, and also that, if a `Psr\Logger\LoggerInterface` service is registered, that is automatically used.

I'm integrating this in an existing expressive project, where I already have a `Psr\Logger\LoggerInterface` service used to log app-related information.

I have configured a different psr3-compliant logger to use with swoole, but this component doesn't let you define it via configuration. Instead, you have to provide your own factory for the `Zend\Expressive\Swoole\Log\AccessLogInterface`.

For that I have created a factory which is basically a copy of the `Zend\Expressive\Swoole\Log\AccessLogFactory`, but it also checks if a configuration like this exists:

```php
return [
   
     'zend-expressive-swoole' => [
        'swoole-http-server' => [
            'logger' => [
                'logger_name' => 'my_logger_service',
            ],
        ],
    ],

];
```

The `my_logger_service` service resolves to a `Psr\Logger\LoggerInterface` instance, and then, my custom factory returns a `Zend\Expressive\Swoole\Log\Psr3AccessLogDecorator` instance wrapping that logger, only if defined, otherwise, it falls back to the `Psr\Logger\LoggerInterface` service, and finally, to a `Zend\Expressive\Swoole\Log\StdoutLogger` instance.

Would you be open to add this behavior to zend-expressive-swoole? If so, I can provide the pull request.

**Comment by weierophinney** [comment]
This would be a fantastic feature - I've labeled it help wanted, and good first issue!

**Comment by acelaya** [comment]
Great! I mostly have it implemented already, so I can provide a PR as soon as I have a minute to do it.
