### ISSUE TITLE
Allow multiple server instances if the port is different

### ISSUE THREAD

**Issue by acelaya** [zendframework/zend-expressive-swoole#58]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-swoole/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-swoole/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I'm currently using swoole in a project where I'm preparing some integration tests where I want to set-up a real app before executing the test suite.

In order to do this, I thought it might make sense to start the swoole server in a different port, but if I already have an instance running, I get the `Server is already running!` error.

Would it make sense (and be possible) to update this module so that it allows to run swoole in multiple ports at the same time?

**Comment by huangzhhui** [comment]
You could modify `$config['zend-expressive-swoole']['swoole-http-server']['options']['pid_file']` to a different path before you start another server.

**Comment by acelaya** [comment]
I was just going to post an answer with that same solution. I've been digging into the code and found that option.

Thanks! :)

**Comment by weierophinney** [comment]
@acelaya and/or @huangzhhui — could one of you provide documentation in this package for this use case, please? I think others will likely have this question!

**Comment by acelaya** [comment]
Absolutely. I can do it

**Comment by acelaya** [comment]
Just created the PR #59
