### ISSUE TITLE
Allow to customize logger used for file reloader

### ISSUE THREAD

**Issue by acelaya** [zendframework/zend-expressive-swoole#63]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-swoole/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-swoole/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I was recently digging into the code and discovered the hot code reloading feature.

I started to play with it and saw the Reloader was getting a logger injected, but I wasn't seeing the messages printed, until I realized it was printing them in a different place because I have a LoggerInterface service.

I was thinking that maybe it makes sense to provide something like what was implemented [here](https://github.com/zendframework/zend-expressive-swoole/pull/55), but for the Reloader.

In fact, what I was expecting at first was the Reloader to share the same logger defined for the swoole server, but from a config point of view, maybe that's confusing. What do you think?

Anyway, regardless the approach, I can provide a PR if you think this makes sense.

**Comment by weierophinney** [comment]
> what I was expecting at first was the Reloader to share the same logger defined for the swoole server

I agree that this is a reasonable expectation!

Looking forward to the PR; please ping me when it is ready.

**Comment by acelaya** [comment]
I have just provided the PR with a few comments there. I'll wait to hear from you.

**Comment by michalbundyra** [comment]
Release with 2.4.0.
