### ISSUE TITLE
Requests without gzip breaks in chrome

### ISSUE THREAD

**Issue by grizzm0** [zendframework/zend-expressive-swoole#66]
Setting `Accept-Encoding: q=0,deflate;q=0` yields `ERR_CONTENT_DECODING_FAILED` in chrome.

So far I've tested it in chrome and postman. The request works fine in postman but breaks in chrome. See screenshot.

![Screenshot 2019-03-23 22 33 29](https://user-images.githubusercontent.com/2905853/54872026-ed7c1300-4dbd-11e9-81ae-d13e6c56c5fd.png)

**Comment by weierophinney** [comment]
This may or may not be a Swoole issue. I have Caddy sitting in front of my Swoole instance (in order to act as a reverse proxy to several sites and provide Lets Encrypt automation), so the issue could be there as well. If you could, it would be good to test this directly against a Swoole site and verify.

**Comment by grizzm0** [comment]
I've tested both against nginx with proxy_pass and directly against swoole. I get the same error in both cases. As a workaround until it's fixed I've set this in my nginx config `proxy_set_header Accept-Encoding "";`

**Comment by grizzm0** [comment]
Anyone knows what could be causing this? Is the error in expressive-swoole or perhaps swoole itself?

We're using expressive-swoole for our new elasticsearch drieven search and product catalog API and got some people complaining that nothing worked during our first AB-test which was tracked back to the non-gzip header error.

I wish to remove the nginx proxy_pass and expose the swoole application directly in the near future but probably can't do that until this is fixed as I would have to disable gzip all together in the application layer.

**Comment by weierophinney** [comment]
Honestly, I cannot recreate this. Assuming that my own site presents the problem, I've tried using both HTTPie and curl, passing the `Accept-Encoding: q=0,deflate;q=0` header, and in each case, I get back a response with `Content-Encoding: deflate`, with the content properly compressed.

At this point, I need some way to reproduce the problem if I am to investigate further. This will likely include:

- a Dockerfile
- a path demonstrating the issue
- a shell script invoking curl or HTTPie to demonstrate how to call the path

**Comment by grizzm0** [comment]
I downloaded an extension to chrome that lets you modify the headers. As I said, it seems to work just fine in postman and I expected it to work with curl aswell.

It must be something that chrome doesn't like about the response. Some of the users who reported the error used IE/edge aswell so I don't think it's chrome specific. It could be some weird header that makes the browsers think it should be decoded.

**Comment by grizzm0** [comment]
This no longer seems to be an issue.

Might just have been a bug in a specific version of chrome.
